USE MangaManagementDB;
GO
CREATE OR ALTER PROCEDURE audit.usp_AuditEvent_Append
    @actor_user_id      UNIQUEIDENTIFIER = NULL,
    @action_code        NVARCHAR(64),
    @entity_type        NVARCHAR(128),
    @entity_id          NVARCHAR(100) = NULL,
    @detail_json        NVARCHAR(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @started_tran BIT = 0;
    DECLARE @lock_result INT;
    DECLARE @actor_role_name NVARCHAR(128) = NULL;

    BEGIN TRY
        IF @detail_json IS NOT NULL AND ISJSON(@detail_json) <> 1
        BEGIN
            ;THROW 50001, 'detail_json must be valid JSON.', 1;
        END;

        IF @@TRANCOUNT = 0
        BEGIN
            SET @started_tran = 1;
            BEGIN TRAN;
        END;

        /*
            Resolve actor role snapshot inside the audit procedure.
            This prevents the backend from passing role-name text manually.
        */
        IF @actor_user_id IS NOT NULL
        BEGIN
            SELECT
                @actor_role_name = r.role_name
            FROM
            (
                SELECT
                    u.user_id,
                    u.role_id
                FROM auth.Users u
                WHERE u.user_id = @actor_user_id
            ) AS actor_user
            INNER JOIN auth.Roles r
                ON r.role_id = actor_user.role_id;

            IF @actor_role_name IS NULL
            BEGIN
                ;THROW 50003, 'Actor user role could not be resolved.', 1;
            END;
        END;

        EXEC @lock_result = sys.sp_getapplock
            @Resource = N'audit_event_append',
            @LockMode = 'Exclusive',
            @LockOwner = 'Transaction',
            @LockTimeout = 10000;

        IF @lock_result < 0
        BEGIN
            ;THROW 50002, 'Could not acquire audit event append lock.', 1;
        END;

        INSERT INTO audit.AuditEvent
        (
            actor_user_id,
            actor_role_name,
            action_code,
            entity_type,
            entity_id,
            detail_json
        )
        VALUES
        (
            @actor_user_id,
            @actor_role_name,
            @action_code,
            @entity_type,
            @entity_id,
            @detail_json
        );

        IF @started_tran = 1
        BEGIN
            COMMIT;
        END;
    END TRY
    BEGIN CATCH
        IF @started_tran = 1 AND XACT_STATE() <> 0
        BEGIN
            ROLLBACK;
        END;

        ;THROW;
    END CATCH
END;
GO
CREATE OR ALTER PROCEDURE auth.usp_User_Create
    @role_name               NVARCHAR(30),
    @username                NVARCHAR(50),
    @email                   NVARCHAR(254),
    @password_hash           NVARCHAR(255),
    @display_name            NVARCHAR(100) = NULL,
    @avatar_file_id          UNIQUEIDENTIFIER = NULL,
    @portfolio_file_id       UNIQUEIDENTIFIER = NULL,

    @created_by_user_id      UNIQUEIDENTIFIER = NULL,

    @new_user_id             UNIQUEIDENTIFIER OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @started_tran BIT = 0;
    DECLARE @detail_json NVARCHAR(MAX);

    DECLARE @resolved_role_id UNIQUEIDENTIFIER;
    DECLARE @resolved_role_name NVARCHAR(30);

    DECLARE @audit_actor_user_id UNIQUEIDENTIFIER;
    DECLARE @audit_entity_id NVARCHAR(100);

    DECLARE @normalized_role_name NVARCHAR(30) = LTRIM(RTRIM(@role_name));
    DECLARE @normalized_username NVARCHAR(50) = LTRIM(RTRIM(@username));
    DECLARE @normalized_email NVARCHAR(254) = LOWER(LTRIM(RTRIM(@email)));
    DECLARE @normalized_display_name NVARCHAR(100) = NULLIF(LTRIM(RTRIM(@display_name)), N'');

    DECLARE @created_user TABLE
    (
        user_id     UNIQUEIDENTIFIER NOT NULL,
        status_code NVARCHAR(30) NOT NULL
    );

    BEGIN TRY
        IF @normalized_display_name IS NULL
        BEGIN
            SET @normalized_display_name = @normalized_username;
        END;

        IF @@TRANCOUNT = 0
        BEGIN
            SET @started_tran = 1;
            BEGIN TRAN;
        END;

        /*
            Resolve requested role name into role_id.
            App passes role name; database stores GUID role_id.
        */
        SELECT
            @resolved_role_id = r.role_id,
            @resolved_role_name = r.role_name
        FROM auth.Roles r
        WHERE UPPER(LTRIM(RTRIM(r.role_name))) = UPPER(@normalized_role_name);

        IF @resolved_role_id IS NULL
        BEGIN
            ;THROW 50015, 'Invalid role name.', 1;
        END;

        /*
            auth.Users.user_id is generated by DEFAULT NEWID().
            Capture the generated GUID using OUTPUT inserted.user_id.
        */
        INSERT INTO auth.Users
        (
            role_id,
            username,
            email,
            password_hash,
            display_name,
            avatar_file_id,
            portfolio_file_id,
            status_code
        )
        OUTPUT
            inserted.user_id,
            inserted.status_code
        INTO @created_user
        (
            user_id,
            status_code
        )
        VALUES
        (
            @resolved_role_id,
            @normalized_username,
            @normalized_email,
            @password_hash,
            @normalized_display_name,
            @avatar_file_id,
            @portfolio_file_id,
            N'PENDING_APPROVAL'
        );

        SELECT
            @new_user_id = user_id
        FROM @created_user;

        /*
            If created by Admin/staff, audit actor is the creator.
            If self-registration, audit actor is the newly created user.
            audit.usp_AuditEvent_Append resolves actor_role_name internally.
        */
        SET @audit_actor_user_id = COALESCE(@created_by_user_id, @new_user_id);
        SET @audit_entity_id = CONVERT(NVARCHAR(36), @new_user_id);

        SELECT @detail_json =
        (
            SELECT
                @new_user_id AS user_id,
                @resolved_role_id AS role_id,
                @resolved_role_name AS role_name,
                @normalized_username AS username,
                @normalized_email AS email,
                @normalized_display_name AS display_name,
                N'PENDING_APPROVAL' AS status_code
            FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
        );

        EXEC audit.usp_AuditEvent_Append
    @actor_user_id = @audit_actor_user_id,
    @action_code = N'USER_REGISTERED',
    @entity_type = N'Users',
    @entity_id = @audit_entity_id,
    @detail_json = @detail_json;

        IF @started_tran = 1
        BEGIN
            COMMIT;
        END;
    END TRY
    BEGIN CATCH
        DECLARE @error_number INT = ERROR_NUMBER();

        IF @started_tran = 1 AND XACT_STATE() <> 0
        BEGIN
            ROLLBACK;
        END;

        IF @error_number IN (2601, 2627)
        BEGIN
            ;THROW 50011, 'Username or email already exists.', 1;
        END;

        ;THROW;
    END CATCH
END;
GO
CREATE OR ALTER PROCEDURE auth.usp_Admin_ChangeUserStatus
    @admin_user_id              UNIQUEIDENTIFIER,
    @target_user_id             UNIQUEIDENTIFIER,
    @new_status_code            NVARCHAR(30),
    @reason                     NVARCHAR(500) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @started_tran BIT = 0;
    DECLARE @lock_result INT;
    DECLARE @lock_resource NVARCHAR(255);

    DECLARE @old_status_code NVARCHAR(30);
    DECLARE @normalized_new_status_code NVARCHAR(30) = UPPER(LTRIM(RTRIM(@new_status_code)));
    DECLARE @normalized_reason NVARCHAR(500) = NULLIF(LTRIM(RTRIM(@reason)), N'');

    DECLARE @audit_entity_id NVARCHAR(100);
    DECLARE @detail_json NVARCHAR(MAX);

    BEGIN TRY
        IF @@TRANCOUNT = 0
        BEGIN
            SET @started_tran = 1;
            BEGIN TRAN;
        END;

        SET @lock_resource = N'auth_user_status_change_' + CONVERT(NVARCHAR(36), @target_user_id);

        EXEC @lock_result = sys.sp_getapplock
            @Resource = @lock_resource,
            @LockMode = 'Exclusive',
            @LockOwner = 'Transaction',
            @LockTimeout = 10000;

        IF @lock_result < 0
        BEGIN
            ;THROW 53101, 'Could not acquire user status change lock.', 1;
        END;

        IF NOT EXISTS
        (
            SELECT 1
            FROM
            (
                SELECT
                    u.user_id,
                    u.role_id
                FROM auth.Users u
                WHERE u.user_id = @admin_user_id
                  AND u.status_code = N'ACTIVE'
            ) AS active_admin
            INNER JOIN auth.Roles r
                ON r.role_id = active_admin.role_id
            WHERE r.role_name = N'Admin'
        )
        BEGIN
            ;THROW 53102, 'Admin user is not active or does not have permission.', 1;
        END;

        SELECT
            @old_status_code = u.status_code
        FROM auth.Users u WITH (UPDLOCK, HOLDLOCK)
        WHERE u.user_id = @target_user_id;

        IF @old_status_code IS NULL
        BEGIN
            ;THROW 53103, 'Target user does not exist.', 1;
        END;

        IF @old_status_code = @normalized_new_status_code
        BEGIN
            IF @started_tran = 1
            BEGIN
                COMMIT;
            END;

            RETURN;
        END;

        UPDATE auth.Users
        SET
            status_code = @normalized_new_status_code
        WHERE user_id = @target_user_id;

        SELECT @detail_json =
        (
            SELECT
                @target_user_id AS user_id,
                @old_status_code AS old_status_code,
                @normalized_new_status_code AS new_status_code,
                @normalized_reason AS reason
            FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
        );

       SET @audit_entity_id = CONVERT(NVARCHAR(36), @target_user_id);

EXEC audit.usp_AuditEvent_Append
    @actor_user_id = @admin_user_id,
    @action_code = N'USER_STATUS_CHANGED',
    @entity_type = N'Users',
    @entity_id = @audit_entity_id,
    @detail_json = @detail_json;

        IF @started_tran = 1
        BEGIN
            COMMIT;
        END;
    END TRY
    BEGIN CATCH
        IF @started_tran = 1 AND XACT_STATE() <> 0
        BEGIN
            ROLLBACK;
        END;

        ;THROW;
    END CATCH
END;
GO
CREATE OR ALTER PROCEDURE auth.usp_User_ResetPassword
    @target_user_id      UNIQUEIDENTIFIER,
    @new_password_hash   NVARCHAR(255),
    @actor_user_id       UNIQUEIDENTIFIER = NULL,
    @reset_mode          NVARCHAR(30),
    @reset_reason        NVARCHAR(500) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @started_tran BIT = 0;
    DECLARE @lock_result INT;
    DECLARE @lock_resource NVARCHAR(255);

    DECLARE @old_status_code NVARCHAR(30);
    DECLARE @normalized_reset_mode NVARCHAR(30) = UPPER(LTRIM(RTRIM(@reset_mode)));
    DECLARE @normalized_reset_reason NVARCHAR(500) = NULLIF(LTRIM(RTRIM(@reset_reason)), N'');

    DECLARE @detail_json NVARCHAR(MAX);
    DECLARE @action_code NVARCHAR(64);

    BEGIN TRY
        IF @normalized_reset_mode NOT IN (N'SELF_CHANGE', N'TOKEN_RESET', N'ADMIN_RESET')
        BEGIN
            ;THROW 52001, 'Invalid reset_mode.', 1;
        END;

        IF @new_password_hash IS NULL OR LEN(LTRIM(RTRIM(@new_password_hash))) < 20
        BEGIN
            ;THROW 52002, 'new_password_hash is invalid.', 1;
        END;

        IF @normalized_reset_mode = N'SELF_CHANGE'
           AND (@actor_user_id IS NULL OR @actor_user_id <> @target_user_id)
        BEGIN
            ;THROW 52004, 'Self password change must be performed by the target user.', 1;
        END;

        IF @normalized_reset_mode = N'ADMIN_RESET'
           AND @actor_user_id IS NULL
        BEGIN
            ;THROW 52005, 'Admin password reset requires an actor user.', 1;
        END;

        IF @@TRANCOUNT = 0
        BEGIN
            SET @started_tran = 1;
            BEGIN TRAN;
        END;

        /*
            Serialize password reset/change for the same target user.
            GUID values should be converted with NVARCHAR(36).
        */
        SET @lock_resource = N'auth_user_password_reset_' + CONVERT(NVARCHAR(36), @target_user_id);

        EXEC @lock_result = sys.sp_getapplock
            @Resource = @lock_resource,
            @LockMode = 'Exclusive',
            @LockOwner = 'Transaction',
            @LockTimeout = 10000;

        IF @lock_result < 0
        BEGIN
            ;THROW 52006, 'Could not acquire password reset lock.', 1;
        END;

        /*
            Admin reset must be performed by an ACTIVE Admin.
        */
        IF @normalized_reset_mode = N'ADMIN_RESET'
        BEGIN
            IF NOT EXISTS
            (
                SELECT 1
                FROM
                (
                    SELECT
                        u.user_id,
                        u.role_id
                    FROM auth.Users u
                    WHERE u.user_id = @actor_user_id
                      AND u.status_code = N'ACTIVE'
                ) AS active_actor
                INNER JOIN auth.Roles r
                    ON r.role_id = active_actor.role_id
                WHERE r.role_name = N'Admin'
            )
            BEGIN
                ;THROW 52007, 'Actor user is not an active Admin.', 1;
            END;
        END;

        /*
            Read target user with update lock.
        */
        SELECT
            @old_status_code = status_code
        FROM auth.Users WITH (UPDLOCK, HOLDLOCK)
        WHERE user_id = @target_user_id;

        IF @old_status_code IS NULL
        BEGIN
            ;THROW 52003, 'Target user does not exist.', 1;
        END;

        /*
            Password reset updates only password_hash.

            It must not approve, reject, disable, or re-enable accounts.
            Therefore:
            - PENDING_APPROVAL stays PENDING_APPROVAL
            - ACTIVE stays ACTIVE
            - REJECTED stays REJECTED
            - DISABLED stays DISABLED
        */
        UPDATE auth.Users
        SET
            password_hash = @new_password_hash
        WHERE user_id = @target_user_id;

        SET @action_code =
            CASE
                WHEN @normalized_reset_mode = N'SELF_CHANGE' THEN N'PASSWORD_CHANGED'
                WHEN @normalized_reset_mode = N'TOKEN_RESET' THEN N'PASSWORD_RESET_BY_TOKEN'
                WHEN @normalized_reset_mode = N'ADMIN_RESET' THEN N'PASSWORD_RESET_BY_ADMIN'
            END;

        SELECT @detail_json =
        (
            SELECT
                @target_user_id AS user_id,
                @old_status_code AS status_code,
                @normalized_reset_mode AS reset_mode,
                @normalized_reset_reason AS reset_reason,
                N'Password hash updated.' AS result
            FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
        );

        DECLARE @audit_entity_id NVARCHAR(100);

SET @audit_entity_id = CONVERT(NVARCHAR(36), @target_user_id);

EXEC audit.usp_AuditEvent_Append
    @actor_user_id = @actor_user_id,
    @action_code = @action_code,
    @entity_type = N'Users',
    @entity_id = @audit_entity_id,
    @detail_json = @detail_json;

        IF @started_tran = 1
        BEGIN
            COMMIT;
        END;
    END TRY
    BEGIN CATCH
        IF @started_tran = 1 AND XACT_STATE() <> 0
        BEGIN
            ROLLBACK;
        END;

        ;THROW;
    END CATCH
END;
GO
CREATE OR ALTER PROCEDURE manga.usp_FileResource_Create
    @file_purpose_code        NVARCHAR(50),
    @original_file_name       NVARCHAR(260),
    @cloudinary_public_id     NVARCHAR(255),
    @cloudinary_secure_url    NVARCHAR(1000),
    @content_type             NVARCHAR(100),
    @file_size_bytes          BIGINT,
    @sha256_hash              CHAR(64),
    @uploaded_by_user_id      UNIQUEIDENTIFIER = NULL,
    @file_resource_id         UNIQUEIDENTIFIER OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @created_file TABLE
    (
        file_resource_id UNIQUEIDENTIFIER NOT NULL
    );

    INSERT INTO manga.FileResource
    (
        file_purpose_code,
        original_file_name,
        cloudinary_public_id,
        cloudinary_secure_url,
        content_type,
        file_size_bytes,
        sha256_hash,
        uploaded_by_user_id
    )
    OUTPUT
        inserted.file_resource_id
    INTO @created_file
    (
        file_resource_id
    )
    VALUES
    (
        @file_purpose_code,
        @original_file_name,
        @cloudinary_public_id,
        @cloudinary_secure_url,
        @content_type,
        @file_size_bytes,
        @sha256_hash,
        @uploaded_by_user_id
    );

    SELECT
        @file_resource_id = file_resource_id
    FROM @created_file;
END;
GO
CREATE OR ALTER PROCEDURE manga.usp_FileResource_SoftDelete
    @file_resource_id UNIQUEIDENTIFIER,
    @deleted_by_user_id UNIQUEIDENTIFIER,
    @delete_reason NVARCHAR(500) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @started_tran BIT = 0;

    DECLARE @old_file_purpose_code NVARCHAR(50);
    DECLARE @old_original_file_name NVARCHAR(260);
    DECLARE @old_cloudinary_public_id NVARCHAR(255);
    DECLARE @old_content_type NVARCHAR(100);
    DECLARE @old_deleted_at_utc DATETIME2(0);

    DECLARE @normalized_delete_reason NVARCHAR(500) = NULLIF(LTRIM(RTRIM(@delete_reason)), N'');
    DECLARE @detail_json NVARCHAR(MAX);
    DECLARE @audit_entity_id NVARCHAR(100);

    BEGIN TRY
        IF @@TRANCOUNT = 0
        BEGIN
            SET @started_tran = 1;
            BEGIN TRAN;
        END;

        SELECT
            @old_file_purpose_code = file_purpose_code,
            @old_original_file_name = original_file_name,
            @old_cloudinary_public_id = cloudinary_public_id,
            @old_content_type = content_type,
            @old_deleted_at_utc = deleted_at_utc
        FROM manga.FileResource WITH (UPDLOCK, HOLDLOCK)
        WHERE file_resource_id = @file_resource_id;

        IF @old_file_purpose_code IS NULL
        BEGIN
            ;THROW 54001, 'File resource does not exist.', 1;
        END;

        IF @old_deleted_at_utc IS NOT NULL
        BEGIN
            ;THROW 54002, 'File resource is already deleted.', 1;
        END;

        UPDATE manga.FileResource
        SET
            deleted_at_utc = SYSUTCDATETIME(),
            deleted_by_user_id = @deleted_by_user_id
        WHERE file_resource_id = @file_resource_id;

        SELECT @detail_json =
        (
            SELECT
                @file_resource_id AS file_resource_id,
                @old_file_purpose_code AS file_purpose_code,
                @old_original_file_name AS original_file_name,
                @old_cloudinary_public_id AS cloudinary_public_id,
                @old_content_type AS content_type,
                @normalized_delete_reason AS delete_reason
            FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
        );

        SET @audit_entity_id = CONVERT(NVARCHAR(36), @file_resource_id);

        EXEC audit.usp_AuditEvent_Append
            @actor_user_id = @deleted_by_user_id,
            @action_code = N'FILE_RESOURCE_SOFT_DELETED',
            @entity_type = N'FileResource',
            @entity_id = @audit_entity_id,
            @detail_json = @detail_json;

        IF @started_tran = 1
        BEGIN
            COMMIT;
        END;
    END TRY
    BEGIN CATCH
        IF @started_tran = 1 AND XACT_STATE() <> 0
        BEGIN
            ROLLBACK;
        END;

        ;THROW;
    END CATCH
END;
GO
CREATE OR ALTER PROCEDURE manga.usp_FileResource_FindActiveDuplicates
    @sha256_hash         CHAR(64),
    @file_size_bytes     BIGINT = NULL,
    @file_purpose_code   NVARCHAR(50) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        file_resource_id,
        file_purpose_code,
        original_file_name,
        cloudinary_public_id,
        cloudinary_secure_url,
        content_type,
        file_size_bytes,
        sha256_hash,
        uploaded_by_user_id,
        uploaded_at_utc
    FROM manga.FileResource
    WHERE sha256_hash = @sha256_hash
      AND deleted_at_utc IS NULL
      AND (@file_size_bytes IS NULL OR file_size_bytes = @file_size_bytes)
      AND (@file_purpose_code IS NULL OR file_purpose_code = @file_purpose_code)
    ORDER BY uploaded_at_utc DESC;
END;
GO
CREATE OR ALTER PROCEDURE auth.usp_User_UpdatePortfolioFile
    @target_user_id              UNIQUEIDENTIFIER,
    @actor_user_id               UNIQUEIDENTIFIER,

    @original_file_name          NVARCHAR(260),
    @cloudinary_public_id        NVARCHAR(255),
    @cloudinary_secure_url       NVARCHAR(1000),
    @content_type                NVARCHAR(100),
    @file_size_bytes             BIGINT,
    @sha256_hash                 CHAR(64),

    @new_portfolio_file_id       UNIQUEIDENTIFIER OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @started_tran BIT = 0;
    DECLARE @lock_result INT;
    DECLARE @lock_resource NVARCHAR(255);

    DECLARE @old_portfolio_file_id UNIQUEIDENTIFIER;
    DECLARE @detail_json NVARCHAR(MAX);
    DECLARE @action_code NVARCHAR(64);
    DECLARE @audit_entity_id NVARCHAR(100);

    BEGIN TRY
        IF @@TRANCOUNT = 0
        BEGIN
            SET @started_tran = 1;
            BEGIN TRAN;
        END;

        SET @lock_resource = N'auth_user_portfolio_update_' + CONVERT(NVARCHAR(36), @target_user_id);

        EXEC @lock_result = sys.sp_getapplock
            @Resource = @lock_resource,
            @LockMode = 'Exclusive',
            @LockOwner = 'Transaction',
            @LockTimeout = 10000;

        IF @lock_result < 0
        BEGIN
            ;THROW 54101, 'Could not acquire user portfolio update lock.', 1;
        END;

        /*
            Permission rule:
            - A user may update their own portfolio.
            - An active Admin may update another user's portfolio.
            This also supports registration-time attachment after the user row is created.
        */
        IF @actor_user_id <> @target_user_id
           AND NOT EXISTS
           (
               SELECT 1
               FROM
               (
                   SELECT
                       u.user_id,
                       u.role_id
                   FROM auth.Users u
                   WHERE u.user_id = @actor_user_id
                     AND u.status_code = N'ACTIVE'
               ) AS active_actor
               INNER JOIN auth.Roles r
                   ON r.role_id = active_actor.role_id
               WHERE r.role_name = N'Admin'
           )
        BEGIN
            ;THROW 54102, 'Actor does not have permission to update this portfolio.', 1;
        END;

        SELECT
            @old_portfolio_file_id = portfolio_file_id
        FROM auth.Users WITH (UPDLOCK, HOLDLOCK)
        WHERE user_id = @target_user_id;

        IF @@ROWCOUNT = 0
        BEGIN
            ;THROW 54103, 'Target user does not exist.', 1;
        END;

        EXEC manga.usp_FileResource_Create
            @file_purpose_code = N'REGISTRATION_PORTFOLIO',
            @original_file_name = @original_file_name,
            @cloudinary_public_id = @cloudinary_public_id,
            @cloudinary_secure_url = @cloudinary_secure_url,
            @content_type = @content_type,
            @file_size_bytes = @file_size_bytes,
            @sha256_hash = @sha256_hash,
            @uploaded_by_user_id = @target_user_id,
            @file_resource_id = @new_portfolio_file_id OUTPUT;

        UPDATE auth.Users
        SET
            portfolio_file_id = @new_portfolio_file_id
        WHERE user_id = @target_user_id;

        SET @action_code =
            CASE
                WHEN @old_portfolio_file_id IS NULL
                    THEN N'REGISTRATION_PORTFOLIO_ATTACHED'
                ELSE N'USER_PORTFOLIO_UPDATED'
            END;

        SELECT @detail_json =
        (
            SELECT
                @target_user_id AS user_id,
                @old_portfolio_file_id AS old_portfolio_file_id,
                @new_portfolio_file_id AS new_portfolio_file_id
            FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
        );

        SET @audit_entity_id = CONVERT(NVARCHAR(36), @target_user_id);

        EXEC audit.usp_AuditEvent_Append
            @actor_user_id = @actor_user_id,
            @action_code = @action_code,
            @entity_type = N'Users',
            @entity_id = @audit_entity_id,
            @detail_json = @detail_json;

        IF @started_tran = 1
        BEGIN
            COMMIT;
        END;
    END TRY
    BEGIN CATCH
        IF @started_tran = 1 AND XACT_STATE() <> 0
        BEGIN
            ROLLBACK;
        END;

        ;THROW;
    END CATCH
END;
GO
CREATE OR ALTER PROCEDURE auth.usp_User_CreateWithOptionalPortfolio
    @role_name                       NVARCHAR(30),
    @username                        NVARCHAR(50),
    @email                           NVARCHAR(254),
    @password_hash                   NVARCHAR(255),
    @display_name                    NVARCHAR(100) = NULL,
    @avatar_file_id                  UNIQUEIDENTIFIER = NULL,

    @portfolio_original_file_name    NVARCHAR(260) = NULL,
    @portfolio_cloudinary_public_id  NVARCHAR(255) = NULL,
    @portfolio_cloudinary_secure_url NVARCHAR(1000) = NULL,
    @portfolio_content_type          NVARCHAR(100) = NULL,
    @portfolio_file_size_bytes       BIGINT = NULL,
    @portfolio_sha256_hash           CHAR(64) = NULL,

    @created_by_user_id              UNIQUEIDENTIFIER = NULL,

    @new_user_id                     UNIQUEIDENTIFIER OUTPUT,
    @portfolio_file_resource_id      UNIQUEIDENTIFIER OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @started_tran BIT = 0;
    DECLARE @has_portfolio BIT = 0;

    BEGIN TRY
        SET @portfolio_file_resource_id = NULL;

        IF @portfolio_cloudinary_public_id IS NOT NULL
        BEGIN
            SET @has_portfolio = 1;
        END;

        IF @@TRANCOUNT = 0
        BEGIN
            SET @started_tran = 1;
            BEGIN TRAN;
        END;

        /*
            Create the user first.
            User ID is generated by auth.Users DEFAULT NEWID()
            and returned through auth.usp_User_Create.
        */
        EXEC auth.usp_User_Create
            @role_name = @role_name,
            @username = @username,
            @email = @email,
            @password_hash = @password_hash,
            @display_name = @display_name,
            @avatar_file_id = @avatar_file_id,
            @portfolio_file_id = NULL,
            @created_by_user_id = @created_by_user_id,
            @new_user_id = @new_user_id OUTPUT;

        /*
            If portfolio metadata is provided, create the FileResource row
            and attach it to the newly created user.
        */
        IF @has_portfolio = 1
        BEGIN
            EXEC auth.usp_User_UpdatePortfolioFile
                @target_user_id = @new_user_id,
                @actor_user_id = @new_user_id,
                @original_file_name = @portfolio_original_file_name,
                @cloudinary_public_id = @portfolio_cloudinary_public_id,
                @cloudinary_secure_url = @portfolio_cloudinary_secure_url,
                @content_type = @portfolio_content_type,
                @file_size_bytes = @portfolio_file_size_bytes,
                @sha256_hash = @portfolio_sha256_hash,
                @new_portfolio_file_id = @portfolio_file_resource_id OUTPUT;
        END;

        IF @started_tran = 1
        BEGIN
            COMMIT;
        END;
    END TRY
    BEGIN CATCH
        IF @started_tran = 1 AND XACT_STATE() <> 0
        BEGIN
            ROLLBACK;
        END;

        THROW;
    END CATCH
END;
GO
CREATE OR ALTER PROCEDURE manga.usp_SeriesProposal_Submit
    @series_id                    UNIQUEIDENTIFIER,
    @submitted_by_user_id          UNIQUEIDENTIFIER,

    @original_file_name            NVARCHAR(260),
    @cloudinary_public_id          NVARCHAR(255),
    @cloudinary_secure_url         NVARCHAR(1000),
    @content_type                  NVARCHAR(100),
    @file_size_bytes               BIGINT,
    @sha256_hash                   CHAR(64),

    @series_proposal_id            UNIQUEIDENTIFIER OUTPUT,
    @proposal_version_no           SMALLINT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @started_tran BIT = 0;
    DECLARE @lock_result INT;
    DECLARE @lock_resource NVARCHAR(255);

    DECLARE @proposal_file_resource_id UNIQUEIDENTIFIER;
    DECLARE @detail_json NVARCHAR(MAX);
    DECLARE @audit_entity_id NVARCHAR(100);

    DECLARE @proposal_title NVARCHAR(200);
    DECLARE @synopsis_snapshot NVARCHAR(MAX);
    DECLARE @genre_snapshot NVARCHAR(100);

    DECLARE @created_proposal TABLE
    (
        series_proposal_id UNIQUEIDENTIFIER NOT NULL
    );

    BEGIN TRY
        IF @@TRANCOUNT = 0
        BEGIN
            SET @started_tran = 1;
            BEGIN TRAN;
        END;

        /*
            Serialize proposal version generation per series.
        */
        SET @lock_resource = N'series_proposal_submit_' + CONVERT(NVARCHAR(36), @series_id);

        EXEC @lock_result = sys.sp_getapplock
            @Resource = @lock_resource,
            @LockMode = 'Exclusive',
            @LockOwner = 'Transaction',
            @LockTimeout = 10000;

        IF @lock_result < 0
        BEGIN
            ;THROW 57001, 'Could not acquire series proposal submit lock.', 1;
        END;

        /*
            Snapshot current Series values inside the database.
            Backend should not pass these snapshot values.
        */
        SELECT
            @proposal_title = s.title,
            @synopsis_snapshot = s.synopsis,
            @genre_snapshot = s.genre
        FROM manga.Series s WITH (UPDLOCK, HOLDLOCK)
        WHERE s.series_id = @series_id;

        IF @proposal_title IS NULL
        BEGIN
            ;THROW 57002, 'Series does not exist.', 1;
        END;

        SELECT
            @proposal_version_no = CONVERT(SMALLINT, ISNULL(MAX(sp.proposal_version_no), 0) + 1)
        FROM manga.SeriesProposal sp WITH (UPDLOCK, HOLDLOCK)
        WHERE sp.series_id = @series_id;

        EXEC manga.usp_FileResource_Create
            @file_purpose_code = N'SERIES_PROPOSAL',
            @original_file_name = @original_file_name,
            @cloudinary_public_id = @cloudinary_public_id,
            @cloudinary_secure_url = @cloudinary_secure_url,
            @content_type = @content_type,
            @file_size_bytes = @file_size_bytes,
            @sha256_hash = @sha256_hash,
            @uploaded_by_user_id = @submitted_by_user_id,
            @file_resource_id = @proposal_file_resource_id OUTPUT;

        INSERT INTO manga.SeriesProposal
        (
            series_id,
            proposal_version_no,
            proposal_title,
            synopsis_snapshot,
            genre_snapshot,
            proposal_file_id,
            status_code,
            submitted_by_user_id,
            submitted_at_utc
        )
        OUTPUT
            inserted.series_proposal_id
        INTO @created_proposal
        (
            series_proposal_id
        )
        VALUES
        (
            @series_id,
            @proposal_version_no,
            @proposal_title,
            @synopsis_snapshot,
            @genre_snapshot,
            @proposal_file_resource_id,
            N'UNDER_EDITORIAL_REVIEW',
            @submitted_by_user_id,
            SYSUTCDATETIME()
        );

        SELECT
            @series_proposal_id = series_proposal_id
        FROM @created_proposal;

        SELECT @detail_json =
        (
            SELECT
                @series_id AS series_id,
                @series_proposal_id AS series_proposal_id,
                @proposal_version_no AS proposal_version_no,
                @proposal_file_resource_id AS proposal_file_resource_id,
                @proposal_title AS proposal_title_snapshot,
                N'UNDER_EDITORIAL_REVIEW' AS status_code
            FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
        );

        SET @audit_entity_id = CONVERT(NVARCHAR(36), @series_proposal_id);

        EXEC audit.usp_AuditEvent_Append
            @actor_user_id = @submitted_by_user_id,
            @action_code = N'SERIES_PROPOSAL_SUBMITTED',
            @entity_type = N'SeriesProposal',
            @entity_id = @audit_entity_id,
            @detail_json = @detail_json;

        IF @started_tran = 1
        BEGIN
            COMMIT;
        END;
    END TRY
    BEGIN CATCH
        IF @started_tran = 1 AND XACT_STATE() <> 0
        BEGIN
            ROLLBACK;
        END;

        ;THROW;
    END CATCH
END;
GO
CREATE OR ALTER PROCEDURE manga.usp_Series_CancelDraft
    @actor_user_id UNIQUEIDENTIFIER,
    @series_id UNIQUEIDENTIFIER,
    @reason NVARCHAR(500) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @started_tran BIT = 0;

    BEGIN TRY
        IF @@TRANCOUNT = 0
        BEGIN
            SET @started_tran = 1;
            BEGIN TRAN;
        END;

        DECLARE @lock_resource NVARCHAR(200) =
            N'manga_series_cancel_' + CONVERT(NVARCHAR(36), @series_id);

        DECLARE @lock_result INT;

        EXEC @lock_result = sys.sp_getapplock
            @Resource = @lock_resource,
            @LockMode = 'Exclusive',
            @LockOwner = 'Transaction',
            @LockTimeout = 10000;

        IF @lock_result < 0
        BEGIN
            ;THROW 57101, 'Could not acquire series cancellation lock.', 1;
        END;

        DECLARE @old_status_code NVARCHAR(50);

        SELECT
            @old_status_code = status_code
        FROM manga.Series
        WHERE series_id = @series_id;

        IF @old_status_code IS NULL
        BEGIN
            ;THROW 57102, 'Series does not exist.', 1;
        END;

        IF @old_status_code <> N'PROPOSAL_DRAFT'
        BEGIN
            ;THROW 57103, 'Only draft series can be cancelled by Mangaka through this procedure.', 1;
        END;

        IF NOT EXISTS
        (
            SELECT 1
            FROM manga.SeriesContributor sc
            INNER JOIN auth.Users u
                ON u.user_id = sc.user_id
            INNER JOIN auth.Roles r
                ON r.role_id = u.role_id
            WHERE sc.series_id = @series_id
              AND sc.user_id = @actor_user_id
              AND sc.end_date IS NULL
              AND u.status_code = N'ACTIVE'
              AND r.role_name = N'Mangaka'
        )
        BEGIN
            ;THROW 57104, 'Only an active Mangaka contributor can cancel this draft series.', 1;
        END;

        UPDATE manga.Series
        SET
            status_code = N'CANCELLED',
            updated_at_utc = SYSUTCDATETIME(),
            updated_by_user_id = @actor_user_id
        WHERE series_id = @series_id;

        DECLARE @audit_entity_id NVARCHAR(100) =
            CONVERT(NVARCHAR(36), @series_id);

        DECLARE @detail_json NVARCHAR(MAX) =
        (
            SELECT
                @old_status_code AS old_status_code,
                N'CANCELLED' AS new_status_code,
                @reason AS reason
            FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
        );

        EXEC audit.usp_AuditEvent_Append
            @actor_user_id = @actor_user_id,
            @action_code = N'SERIES_DRAFT_CANCELLED',
            @entity_type = N'Series',
            @entity_id = @audit_entity_id,
            @detail_json = @detail_json;

        IF @started_tran = 1
        BEGIN
            COMMIT;
        END;
    END TRY
    BEGIN CATCH
        IF @started_tran = 1 AND XACT_STATE() <> 0
        BEGIN
            ROLLBACK;
        END;

        ;THROW;
    END CATCH;
END;
GO
CREATE OR ALTER PROCEDURE manga.usp_SeriesContributor_Add
    @actor_user_id UNIQUEIDENTIFIER,
    @series_id UNIQUEIDENTIFIER,
    @user_id UNIQUEIDENTIFIER,
    @notes NVARCHAR(500) = NULL,
    @new_series_contributor_id UNIQUEIDENTIFIER OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @started_tran BIT = 0;

    BEGIN TRY
        IF @@TRANCOUNT = 0
        BEGIN
            SET @started_tran = 1;
            BEGIN TRAN;
        END;

        --------------------------------------------------------------------
        -- 1. Lock contributor changes for this series
        --------------------------------------------------------------------
        DECLARE @lock_resource NVARCHAR(200) =
            N'manga_series_contributor_add_' + CONVERT(NVARCHAR(36), @series_id);

        DECLARE @lock_result INT;

        EXEC @lock_result = sys.sp_getapplock
            @Resource = @lock_resource,
            @LockMode = 'Exclusive',
            @LockOwner = 'Transaction',
            @LockTimeout = 10000;

        IF @lock_result < 0
        BEGIN
            ;THROW 57201, 'Could not acquire series contributor lock.', 1;
        END;

        --------------------------------------------------------------------
        -- 2. Series must exist and must not be terminal
        --------------------------------------------------------------------
        DECLARE @series_status_code NVARCHAR(50);

        SELECT
            @series_status_code = s.status_code
        FROM manga.Series s
        WHERE s.series_id = @series_id;

        IF @series_status_code IS NULL
        BEGIN
            ;THROW 57202, 'Series does not exist.', 1;
        END;

        IF @series_status_code IN (N'CANCELLED', N'COMPLETED')
        BEGIN
            ;THROW 57203, 'Cannot add contributors to cancelled or completed series.', 1;
        END;

        --------------------------------------------------------------------
        -- 3. Target user must be active
        --------------------------------------------------------------------
        IF NOT EXISTS
        (
            SELECT 1
            FROM auth.Users u
            WHERE u.user_id = @user_id
              AND u.status_code = N'ACTIVE'
        )
        BEGIN
            ;THROW 57204, 'Target user does not exist or is not active.', 1;
        END;

        --------------------------------------------------------------------
        -- 4. Actor permission
        --
        -- Initial creator case:
        --   allowed when there are no active contributors yet,
        --   actor = target user,
        --   actor is active Mangaka.
        --
        -- Normal contributor management case:
        --   allowed when actor is already an active Mangaka contributor.
        --------------------------------------------------------------------
        DECLARE @has_active_contributor BIT = 0;

        IF EXISTS
        (
            SELECT 1
            FROM manga.SeriesContributor sc
            WHERE sc.series_id = @series_id
              AND sc.end_date IS NULL
        )
        BEGIN
            SET @has_active_contributor = 1;
        END;

        DECLARE @actor_is_active_mangaka BIT = 0;

        IF EXISTS
        (
            SELECT 1
            FROM auth.Users u
            INNER JOIN auth.Roles r
                ON r.role_id = u.role_id
            WHERE u.user_id = @actor_user_id
              AND u.status_code = N'ACTIVE'
              AND r.role_name = N'Mangaka'
        )
        BEGIN
            SET @actor_is_active_mangaka = 1;
        END;

        IF @has_active_contributor = 0
        BEGIN
            IF @actor_user_id <> @user_id OR @actor_is_active_mangaka = 0
            BEGIN
                ;THROW 57205, 'Only the active Mangaka creator can be added as the initial series contributor.', 1;
            END;
        END;
        ELSE
        BEGIN
            IF NOT EXISTS
            (
                SELECT 1
                FROM manga.SeriesContributor sc
                INNER JOIN auth.Users u
                    ON u.user_id = sc.user_id
                INNER JOIN auth.Roles r
                    ON r.role_id = u.role_id
                WHERE sc.series_id = @series_id
                  AND sc.user_id = @actor_user_id
                  AND sc.end_date IS NULL
                  AND u.status_code = N'ACTIVE'
                  AND r.role_name = N'Mangaka'
            )
            BEGIN
                ;THROW 57206, 'Only an active Mangaka contributor can add contributors to this series.', 1;
            END;
        END;
        --------------------------------------------------------------------
        -- 6. Insert contributor
        --------------------------------------------------------------------
        DECLARE @created_contributor TABLE
        (
            series_contributor_id UNIQUEIDENTIFIER NOT NULL
        );

        INSERT INTO manga.SeriesContributor
        (
            series_id,
            user_id,
            notes
        )
        OUTPUT inserted.series_contributor_id
        INTO @created_contributor(series_contributor_id)
        VALUES
        (
            @series_id,
            @user_id,
            @notes
        );

        SELECT
            @new_series_contributor_id = series_contributor_id
        FROM @created_contributor;

        --------------------------------------------------------------------
        -- 7. Audit
        --------------------------------------------------------------------
        DECLARE @audit_entity_id NVARCHAR(100) =
            CONVERT(NVARCHAR(36), @new_series_contributor_id);

        DECLARE @detail_json NVARCHAR(MAX) =
        (
            SELECT
                @series_id AS series_id,
                @user_id AS contributor_user_id,
                @notes AS notes
            FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
        );

        EXEC audit.usp_AuditEvent_Append
            @actor_user_id = @actor_user_id,
            @action_code = N'SERIES_CONTRIBUTOR_ADDED',
            @entity_type = N'SeriesContributor',
            @entity_id = @audit_entity_id,
            @detail_json = @detail_json;

        IF @started_tran = 1
        BEGIN
            COMMIT;
        END;
    END TRY
    BEGIN CATCH
        IF @started_tran = 1 AND XACT_STATE() <> 0
        BEGIN
            ROLLBACK;
        END;

        ;THROW;
    END CATCH;
END;
GO
USE MangaManagementDB;
GO
CREATE OR ALTER PROCEDURE manga.usp_Series_Create
    @actor_user_id UNIQUEIDENTIFIER,

    @title NVARCHAR(200),
    @slug NVARCHAR(220),
    @synopsis NVARCHAR(MAX),
    @genre NVARCHAR(100),
    @content_language_code NVARCHAR(10) = N'ja',
    @source_series_id UNIQUEIDENTIFIER = NULL,
    @publication_frequency_code NVARCHAR(50) = NULL,

    @cover_original_file_name NVARCHAR(260) = NULL,
    @cover_cloudinary_public_id NVARCHAR(255) = NULL,
    @cover_cloudinary_secure_url NVARCHAR(1000) = NULL,
    @cover_content_type NVARCHAR(100) = NULL,
    @cover_file_size_bytes BIGINT = NULL,
    @cover_sha256_hash CHAR(64) = NULL,

    @new_series_id UNIQUEIDENTIFIER OUTPUT,
    @cover_file_resource_id UNIQUEIDENTIFIER OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @started_tran BIT = 0;

    BEGIN TRY
        IF @@TRANCOUNT = 0
        BEGIN
            SET @started_tran = 1;
            BEGIN TRAN;
        END;

        SET @cover_file_resource_id = NULL;

        --------------------------------------------------------------------
        -- 1. Actor permission: only active Mangaka can create series draft
        --------------------------------------------------------------------
        IF NOT EXISTS
        (
            SELECT 1
            FROM auth.Users u
            INNER JOIN auth.Roles r
                ON r.role_id = u.role_id
            WHERE u.user_id = @actor_user_id
              AND u.status_code = N'ACTIVE'
              AND r.role_name = N'Mangaka'
        )
        BEGIN
            ;THROW 57301, 'Only an active Mangaka can create a series draft.', 1;
        END;

        --------------------------------------------------------------------
        -- 2. Optional cover metadata group validation
        --------------------------------------------------------------------
        DECLARE @has_cover_metadata BIT = 0;

        IF @cover_original_file_name IS NOT NULL
           OR @cover_cloudinary_public_id IS NOT NULL
           OR @cover_cloudinary_secure_url IS NOT NULL
           OR @cover_content_type IS NOT NULL
           OR @cover_file_size_bytes IS NOT NULL
           OR @cover_sha256_hash IS NOT NULL
        BEGIN
            SET @has_cover_metadata = 1;
        END;

        IF @has_cover_metadata = 1
           AND
           (
               @cover_original_file_name IS NULL
               OR @cover_cloudinary_public_id IS NULL
               OR @cover_cloudinary_secure_url IS NULL
               OR @cover_content_type IS NULL
               OR @cover_file_size_bytes IS NULL
               OR @cover_sha256_hash IS NULL
           )
        BEGIN
            ;THROW 57302, 'Cover file metadata is incomplete.', 1;
        END;

        --------------------------------------------------------------------
        -- 3. Create FileResource for cover if metadata exists
        --------------------------------------------------------------------
        IF @has_cover_metadata = 1
        BEGIN
            EXEC manga.usp_FileResource_Create
                @file_purpose_code = N'SERIES_COVER',
                @original_file_name = @cover_original_file_name,
                @cloudinary_public_id = @cover_cloudinary_public_id,
                @cloudinary_secure_url = @cover_cloudinary_secure_url,
                @content_type = @cover_content_type,
                @file_size_bytes = @cover_file_size_bytes,
                @sha256_hash = @cover_sha256_hash,
                @uploaded_by_user_id = @actor_user_id,
                @file_resource_id = @cover_file_resource_id OUTPUT;
        END;

        --------------------------------------------------------------------
        -- 4. Insert series draft
        --
        -- Table defaults should handle:
        -- - series_id = NEWID()
        -- - status_code = PROPOSAL_DRAFT
        -- - created_at_utc = SYSUTCDATETIME()
        --------------------------------------------------------------------
        DECLARE @created_series TABLE
        (
            series_id UNIQUEIDENTIFIER NOT NULL
        );

        INSERT INTO manga.Series
        (
            title,
            slug,
            synopsis,
            genre,
            cover_file_id,
            content_language_code,
            source_series_id,
            publication_frequency_code
        )
        OUTPUT inserted.series_id
        INTO @created_series(series_id)
        VALUES
        (
            @title,
            @slug,
            @synopsis,
            @genre,
            @cover_file_resource_id,
            @content_language_code,
            @source_series_id,
            @publication_frequency_code
        );

        SELECT
            @new_series_id = series_id
        FROM @created_series;

        --------------------------------------------------------------------
        -- 5. Add creator as initial contributor
        --------------------------------------------------------------------
        DECLARE @new_series_contributor_id UNIQUEIDENTIFIER;

        EXEC manga.usp_SeriesContributor_Add
            @actor_user_id = @actor_user_id,
            @series_id = @new_series_id,
            @user_id = @actor_user_id,
            @notes = N'Creator',
            @new_series_contributor_id = @new_series_contributor_id OUTPUT;

        --------------------------------------------------------------------
        -- 6. Audit
        --------------------------------------------------------------------
        DECLARE @audit_entity_id NVARCHAR(100) =
            CONVERT(NVARCHAR(36), @new_series_id);

        DECLARE @detail_json NVARCHAR(MAX) =
        (
            SELECT
                @title AS title,
                @slug AS slug,
                @synopsis AS synopsis,
                @genre AS genre,
                @content_language_code AS content_language_code,
                @source_series_id AS source_series_id,
                @publication_frequency_code AS publication_frequency_code,
                @cover_file_resource_id AS cover_file_id,
                @new_series_contributor_id AS creator_series_contributor_id
            FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
        );

        EXEC audit.usp_AuditEvent_Append
            @actor_user_id = @actor_user_id,
            @action_code = N'SERIES_CREATED',
            @entity_type = N'Series',
            @entity_id = @audit_entity_id,
            @detail_json = @detail_json;

        IF @started_tran = 1
        BEGIN
            COMMIT;
        END;
    END TRY
    BEGIN CATCH
        IF @started_tran = 1 AND XACT_STATE() <> 0
        BEGIN
            ROLLBACK;
        END;

        ;THROW;
    END CATCH;
END;
GO
USE MangaManagementDB;
GO

CREATE OR ALTER PROCEDURE manga.usp_PageRegion_Create
    @actor_user_id UNIQUEIDENTIFIER,
    @chapter_page_version_id UNIQUEIDENTIFIER,

    @type_code NVARCHAR(80),
    @region_label NVARCHAR(100) = NULL,

    @x DECIMAL(10, 2),
    @y DECIMAL(10, 2),
    @width DECIMAL(10, 2),
    @height DECIMAL(10, 2),

    @confidence_score DECIMAL(5, 4) = NULL,
    @source_type NVARCHAR(20) = N'MANUAL',
    @original_text NVARCHAR(MAX) = NULL,

    @new_page_region_id UNIQUEIDENTIFIER OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @started_tran BIT = 0;

    BEGIN TRY
        IF @@TRANCOUNT = 0
        BEGIN
            SET @started_tran = 1;
            BEGIN TRAN;
        END;

        --------------------------------------------------------------------
        -- Permission check:
        -- Actor must be an active SeriesContributor for the series that owns
        -- the selected ChapterPageVersion.
        --------------------------------------------------------------------
        IF NOT EXISTS
        (
            SELECT 1
            FROM manga.ChapterPageVersion cpv
            INNER JOIN manga.ChapterPage cp
                ON cp.chapter_page_id = cpv.chapter_page_id
            INNER JOIN manga.Chapter ch
                ON ch.chapter_id = cp.chapter_id
            INNER JOIN manga.SeriesContributor sc
                ON sc.series_id = ch.series_id
            INNER JOIN auth.Users u
                ON u.user_id = sc.user_id
            WHERE cpv.chapter_page_version_id = @chapter_page_version_id
              AND sc.user_id = @actor_user_id
              AND sc.end_date IS NULL
              AND u.status_code = N'ACTIVE'
        )
        BEGIN
            ;THROW 57401, 'User is not an active contributor for the series that owns this page version.', 1;
        END;

        --------------------------------------------------------------------
        -- Insert PageRegion.
        -- Let table constraints enforce:
        -- - valid chapter_page_version_id FK
        -- - valid type_code
        -- - valid source_type
        -- - width > 0 and height > 0
        -- - confidence_score range
        -- - AI requires confidence_score
        -- - MANUAL requires confidence_score NULL
        --------------------------------------------------------------------
        DECLARE @created_region TABLE
        (
            page_region_id UNIQUEIDENTIFIER NOT NULL
        );

        INSERT INTO manga.PageRegion
        (
            chapter_page_version_id,
            type_code,
            region_label,
            x,
            y,
            width,
            height,
            confidence_score,
            source_type,
            original_text,
            created_by_user_id
        )
        OUTPUT inserted.page_region_id
        INTO @created_region(page_region_id)
        VALUES
        (
            @chapter_page_version_id,
            @type_code,
            @region_label,
            @x,
            @y,
            @width,
            @height,
            @confidence_score,
            @source_type,
            @original_text,
            @actor_user_id
        );

        SELECT
            @new_page_region_id = page_region_id
        FROM @created_region;

        --------------------------------------------------------------------
        -- Audit
        --------------------------------------------------------------------
        DECLARE @audit_entity_id NVARCHAR(100) =
            CONVERT(NVARCHAR(36), @new_page_region_id);

        DECLARE @detail_json NVARCHAR(MAX) =
        (
            SELECT
                @chapter_page_version_id AS chapter_page_version_id,
                @type_code AS type_code,
                @region_label AS region_label,
                @x AS x,
                @y AS y,
                @width AS width,
                @height AS height,
                @confidence_score AS confidence_score,
                @source_type AS source_type
            FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
        );

        EXEC audit.usp_AuditEvent_Append
            @actor_user_id = @actor_user_id,
            @action_code = N'PAGE_REGION_CREATED',
            @entity_type = N'PageRegion',
            @entity_id = @audit_entity_id,
            @detail_json = @detail_json;

        IF @started_tran = 1
        BEGIN
            COMMIT;
        END;
    END TRY
    BEGIN CATCH
        IF @started_tran = 1 AND XACT_STATE() <> 0
        BEGIN
            ROLLBACK;
        END;

        ;THROW;
    END CATCH;
END;
GO
USE MangaManagementDB;
GO

CREATE OR ALTER PROCEDURE manga.usp_PageRegion_CreateBatch
    @actor_user_id UNIQUEIDENTIFIER,
    @chapter_page_version_id UNIQUEIDENTIFIER,
    @regions_json NVARCHAR(MAX),
    @created_count INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @started_tran BIT = 0;

    BEGIN TRY
        IF @@TRANCOUNT = 0
        BEGIN
            SET @started_tran = 1;
            BEGIN TRAN;
        END;

        SET @created_count = 0;

        --------------------------------------------------------------------
        -- 1. Permission check
        -- Actor must be an active contributor of the series that owns the
        -- selected chapter_page_version_id.
        --------------------------------------------------------------------
        IF NOT EXISTS
        (
            SELECT 1
            FROM manga.ChapterPageVersion cpv
            INNER JOIN manga.ChapterPage cp
                ON cp.chapter_page_id = cpv.chapter_page_id
            INNER JOIN manga.Chapter ch
                ON ch.chapter_id = cp.chapter_id
            INNER JOIN manga.SeriesContributor sc
                ON sc.series_id = ch.series_id
            WHERE cpv.chapter_page_version_id = @chapter_page_version_id
              AND sc.user_id = @actor_user_id
              AND sc.end_date IS NULL
        )
        BEGIN
            ;THROW 57411, 'User is not an active contributor for the series that owns this page version.', 1;
        END;

        --------------------------------------------------------------------
        -- 2. Validate JSON input
        --------------------------------------------------------------------
        IF @regions_json IS NULL OR LTRIM(RTRIM(@regions_json)) = N''
        BEGIN
            ;THROW 57412, 'regions_json is required.', 1;
        END;

        IF ISJSON(@regions_json) <> 1
        BEGIN
            ;THROW 57413, 'regions_json must be valid JSON.', 1;
        END;

        -- Expect a JSON array
        IF LEFT(LTRIM(@regions_json), 1) <> N'['
        BEGIN
            ;THROW 57414, 'regions_json must be a JSON array.', 1;
        END;

        --------------------------------------------------------------------
        -- 3. Parse JSON into a table variable
        --
        -- Expected JSON shape:
        -- [
        --   {
        --     "type_code": "PANEL",
        --     "region_label": "Panel 1",
        --     "x": 10.00,
        --     "y": 20.00,
        --     "width": 100.00,
        --     "height": 150.00,
        --     "confidence_score": 0.9345,
        --     "source_type": "AI",
        --     "original_text": null
        --   },
        --   ...
        -- ]
        --------------------------------------------------------------------
        DECLARE @parsed_regions TABLE
        (
            row_no INT NOT NULL,
            type_code NVARCHAR(80) NULL,
            region_label NVARCHAR(100) NULL,
            x DECIMAL(10, 2) NULL,
            y DECIMAL(10, 2) NULL,
            width DECIMAL(10, 2) NULL,
            height DECIMAL(10, 2) NULL,
            confidence_score DECIMAL(5, 4) NULL,
            source_type NVARCHAR(20) NULL,
            original_text NVARCHAR(MAX) NULL
        );

        INSERT INTO @parsed_regions
        (
            row_no,
            type_code,
            region_label,
            x,
            y,
            width,
            height,
            confidence_score,
            source_type,
            original_text
        )
        SELECT
            TRY_CAST(j.[key] AS INT) + 1 AS row_no,
            p.type_code,
            p.region_label,
            p.x,
            p.y,
            p.width,
            p.height,
            p.confidence_score,
            p.source_type,
            p.original_text
        FROM OPENJSON(@regions_json) j
        CROSS APPLY OPENJSON(j.value)
        WITH
        (
            type_code NVARCHAR(80) '$.type_code',
            region_label NVARCHAR(100) '$.region_label',
            x DECIMAL(10, 2) '$.x',
            y DECIMAL(10, 2) '$.y',
            width DECIMAL(10, 2) '$.width',
            height DECIMAL(10, 2) '$.height',
            confidence_score DECIMAL(5, 4) '$.confidence_score',
            source_type NVARCHAR(20) '$.source_type',
            original_text NVARCHAR(MAX) '$.original_text'
        ) p;

        IF NOT EXISTS (SELECT 1 FROM @parsed_regions)
        BEGIN
            ;THROW 57415, 'regions_json must contain at least one region object.', 1;
        END;

        --------------------------------------------------------------------
        -- 4. Insert PageRegion rows
        --
        -- The PageRegion table constraints enforce:
        -- - FK to valid chapter_page_version_id
        -- - type_code list
        -- - source_type list
        -- - positive width/height
        -- - confidence range
        -- - AI/MANUAL confidence rule
        --------------------------------------------------------------------
        DECLARE @created_regions TABLE
        (
            page_region_id UNIQUEIDENTIFIER NOT NULL
        );

        INSERT INTO manga.PageRegion
        (
            chapter_page_version_id,
            type_code,
            region_label,
            x,
            y,
            width,
            height,
            confidence_score,
            source_type,
            original_text,
            created_by_user_id
        )
        OUTPUT inserted.page_region_id
        INTO @created_regions(page_region_id)
        SELECT
            @chapter_page_version_id,
            pr.type_code,
            pr.region_label,
            pr.x,
            pr.y,
            pr.width,
            pr.height,
            pr.confidence_score,
            pr.source_type,
            pr.original_text,
            @actor_user_id
        FROM @parsed_regions pr
        ORDER BY pr.row_no;

        SELECT
            @created_count = COUNT(*)
        FROM @created_regions;

        --------------------------------------------------------------------
        -- 5. Audit one batch event
        --------------------------------------------------------------------
        DECLARE @audit_entity_id NVARCHAR(100) =
            CONVERT(NVARCHAR(36), @chapter_page_version_id);

        DECLARE @detail_json NVARCHAR(MAX) =
        (
            SELECT
                @chapter_page_version_id AS chapter_page_version_id,
                @created_count AS created_count
            FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
        );

        EXEC audit.usp_AuditEvent_Append
            @actor_user_id = @actor_user_id,
            @action_code = N'PAGE_REGIONS_CREATED_BATCH',
            @entity_type = N'ChapterPageVersion',
            @entity_id = @audit_entity_id,
            @detail_json = @detail_json;

        --------------------------------------------------------------------
        -- 6. Return created IDs as a result set
        --------------------------------------------------------------------
        SELECT
            page_region_id
        FROM @created_regions;

        IF @started_tran = 1
        BEGIN
            COMMIT;
        END;
    END TRY
    BEGIN CATCH
        IF @started_tran = 1 AND XACT_STATE() <> 0
        BEGIN
            ROLLBACK;
        END;

        ;THROW;
    END CATCH;
END;
GO