INSERT INTO [auth].[Users] (
    [username], 
    [email], 
    [password_hash], 
    [role_id], 
    [STATUS], 
    [created_at]
)
VALUES 
(
    'TestMangaka',
    'mangaka@test.com',
    '$2a$12$eBGlrcdEPsP8c6yDmKhnv.OojpFaPqmJ.DcYRswLWEFZAYTwGNDtq',
    1,
    'ACTIVE',
    SYSUTCDATETIME()
),
(
    'TestEditor',
    'editor@test.com',
    '$2a$12$eBGlrcdEPsP8c6yDmKhnv.OojpFaPqmJ.DcYRswLWEFZAYTwGNDtq',
    3,
    'ACTIVE',
    SYSUTCDATETIME()
),
(
    'TestAdmin',
    'admin@test.com',
    '$2a$12$eBGlrcdEPsP8c6yDmKhnv.OojpFaPqmJ.DcYRswLWEFZAYTwGNDtq',
    6,
    'ACTIVE',
    SYSUTCDATETIME()
);
