// <auto-generated />
using System;
using MangaManagementSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<long>("AuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditEventId"));

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActorRoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<string>("DetailJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("AuditEventId");

                    b.HasIndex("ActorUserId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_event_actor_time");

                    b.HasIndex("EntityType", "EntityId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_event_entity_time");

                    b.ToTable("AuditEvent", "audit", t =>
                        {
                            t.HasCheckConstraint("CK_AuditEvent_DetailJson", "[DetailJson] IS NULL OR ISJSON([DetailJson]) = 1");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.Chapter", b =>
                {
                    b.Property<long>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChapterId"));

                    b.Property<string>("ChapterNumberLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChapterTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PlannedReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("SeriesId")
                        .HasColumnType("bigint");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("DRAFT");

                    b.HasKey("ChapterId");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_chapter_series_id");

                    b.HasIndex("StatusCode")
                        .HasDatabaseName("ix_chapter_status_code");

                    b.HasIndex("SeriesId", "ChapterNumberLabel")
                        .IsUnique();

                    b.ToTable("Chapter", "manga", t =>
                        {
                            t.HasCheckConstraint("CK_Chapter_StatusCode", "[StatusCode] IN ('DRAFT','RELEASED','ARCHIVED')");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.ChapterEditorialReview", b =>
                {
                    b.Property<long>("ChapterEditorialReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChapterEditorialReviewId"));

                    b.Property<long>("ChapterId")
                        .HasColumnType("bigint");

                    b.Property<string>("DecisionCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MarkupFileId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReviewerUserId")
                        .HasColumnType("int");

                    b.HasKey("ChapterEditorialReviewId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("MarkupFileId");

                    b.HasIndex("ReviewerUserId");

                    b.ToTable("ChapterEditorialReview", "manga", t =>
                        {
                            t.HasCheckConstraint("CK_ChapterEditorialReview_DecisionCode", "[DecisionCode] IN ('APPROVED','REVISION_REQUESTED','CANCELLED')");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.ChapterPage", b =>
                {
                    b.Property<long>("ChapterPageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChapterPageId"));

                    b.Property<long>("ChapterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("PageNo")
                        .HasColumnType("int");

                    b.Property<string>("PageNotes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChapterPageId");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_chapter_page_chapter_id");

                    b.HasIndex("ChapterId", "PageNo")
                        .IsUnique()
                        .HasDatabaseName("ux_chapter_page_active_page_no")
                        .HasFilter("[DeletedAtUtc] IS NULL");

                    b.ToTable("ChapterPage", "manga");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.ChapterPageAnnotation", b =>
                {
                    b.Property<long>("ChapterPageAnnotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChapterPageAnnotationId"));

                    b.Property<int>("AnnotatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("AnnotationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("PageRegionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("int");

                    b.HasKey("ChapterPageAnnotationId");

                    b.HasIndex("AnnotatedByUserId");

                    b.HasIndex("PageRegionId");

                    b.HasIndex("ResolvedByUserId");

                    b.ToTable("ChapterPageAnnotation", "manga", t =>
                        {
                            t.HasCheckConstraint("CK_ChapterPageAnnotation_IssueTypeCode", "[IssueTypeCode] IN ('TRANSLATION_ERROR','ART_ERROR','LAYOUT_ERROR','OTHER')");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.ChapterPageTask", b =>
                {
                    b.Property<long>("ChapterPageTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChapterPageTaskId"));

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<long?>("CompletedPageVersionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("int");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("ASSIGNED");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChapterPageTaskId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CompletedPageVersionId");

                    b.ToTable("ChapterPageTask", "manga", t =>
                        {
                            t.HasCheckConstraint("CK_ChapterPageTask_PriorityLevel", "[PriorityLevel] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_ChapterPageTask_StatusCode", "[StatusCode] IN ('ASSIGNED','IN_PROGRESS','COMPLETED','CANCELLED')");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.ChapterPageTaskRegion", b =>
                {
                    b.Property<long>("ChapterPageTaskRegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChapterPageTaskRegionId"));

                    b.Property<long>("ChapterPageTaskId")
                        .HasColumnType("bigint");

                    b.Property<long>("PageRegionId")
                        .HasColumnType("bigint");

                    b.HasKey("ChapterPageTaskRegionId");

                    b.HasIndex("ChapterPageTaskId");

                    b.HasIndex("PageRegionId");

                    b.ToTable("ChapterPageTaskRegion", "manga");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.ChapterPageVersion", b =>
                {
                    b.Property<long>("ChapterPageVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChapterPageVersionId"));

                    b.Property<long>("ChapterPageId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCurrentVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("PageFileId")
                        .HasColumnType("bigint");

                    b.Property<short>("VersionNo")
                        .HasColumnType("smallint");

                    b.Property<string>("VersionNote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChapterPageVersionId");

                    b.HasIndex("ChapterPageId")
                        .HasDatabaseName("ix_chapter_page_chapter_id");

                    b.HasIndex("IsCurrentVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_chapter_page_version_current")
                        .HasFilter("[IsCurrentVersion] = 1");

                    b.HasIndex("PageFileId");

                    b.HasIndex("ChapterPageId", "VersionNo")
                        .IsUnique();

                    b.ToTable("ChapterPageVersion", "manga");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.ChapterReaderVoteSnapshot", b =>
                {
                    b.Property<long>("ChapterReaderVoteSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChapterReaderVoteSnapshotId"));

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("ChapterId")
                        .HasColumnType("bigint");

                    b.Property<int?>("EnteredByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReaderVoteCount")
                        .HasColumnType("int");

                    b.HasKey("ChapterReaderVoteSnapshotId");

                    b.HasIndex("ChapterId")
                        .IsUnique();

                    b.HasIndex("EnteredByUserId");

                    b.ToTable("ChapterReaderVoteSnapshot", "manga", t =>
                        {
                            t.HasCheckConstraint("CK_ChapterReaderVoteSnapshot_AverageRating", "[AverageRating] BETWEEN 0 AND 10");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.FileResource", b =>
                {
                    b.Property<long>("FileResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FileResourceId"));

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CloudinarySecureUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("FilePurposeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Sha256Hash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("FileResourceId");

                    b.HasIndex("FilePurposeCode")
                        .HasDatabaseName("ix_file_resource_purpose_code");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_file_resource_uploaded_by");

                    b.HasIndex("FilePurposeCode", "DeletedAtUtc")
                        .HasDatabaseName("ix_file_resource_active_by_purpose")
                        .HasFilter("[DeletedAtUtc] IS NULL");

                    b.ToTable("FileResource", "manga", t =>
                        {
                            t.HasCheckConstraint("CK_FileResource_PurposeCode", "[FilePurposeCode] IN ('COVER','PORTFOLIO','PAGE','MARKUP','OTHER')");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NotificationTypeCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("SYSTEM_MESSAGE");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedEntityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NotificationId");

                    b.HasIndex("RecipientUserId")
                        .HasDatabaseName("ix_notification_unread_recipient")
                        .HasFilter("[ReadAtUtc] IS NULL");

                    b.HasIndex("RelatedEntityType", "RelatedEntityId")
                        .HasDatabaseName("ix_notification_related_entity")
                        .HasFilter("[RelatedEntityType] IS NOT NULL AND [RelatedEntityId] IS NOT NULL");

                    b.HasIndex("RecipientUserId", "ReadAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_notification_recipient_read_created");

                    b.ToTable("Notification", "manga");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.PageRegion", b =>
                {
                    b.Property<long>("PageRegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PageRegionId"));

                    b.Property<long>("ChapterPageVersionId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Height")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OriginalText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("MANUAL");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasDefaultValue("OTHER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Width")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("X")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Y")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PageRegionId");

                    b.HasIndex("TypeCode")
                        .HasDatabaseName("ix_page_region_type");

                    b.HasIndex("ChapterPageVersionId", "TypeCode")
                        .HasDatabaseName("ix_page_region_version_type");

                    b.ToTable("PageRegion", "manga", t =>
                        {
                            t.HasCheckConstraint("CK_PageRegion_SourceType", "[SourceType] IN ('AI','MANUAL')");

                            t.HasCheckConstraint("CK_PageRegion_TypeCode", "[TypeCode] IN ('PANEL','SPEECH_BUBBLE','CHARACTER','SFX_TEXT','BACKGROUND','OTHER')");

                            t.HasCheckConstraint("CK_PageRegion_Width_Height", "[Width] > 0 AND [Height] > 0");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.Role", b =>
                {
                    b.Property<short>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", "auth");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.Series", b =>
                {
                    b.Property<long>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SeriesId"));

                    b.Property<string>("ContentLanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("ja");

                    b.Property<long?>("CoverFileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PublicationFrequencyCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SeriesCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<long?>("SourceSeriesId")
                        .HasColumnType("bigint");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PROPOSAL_DRAFT");

                    b.Property<string>("Synopsis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("SeriesId");

                    b.HasIndex("CoverFileId");

                    b.HasIndex("SeriesCode")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL");

                    b.HasIndex("SourceSeriesId");

                    b.HasIndex("StatusCode")
                        .HasDatabaseName("ix_series_current_status_code");

                    b.ToTable("Series", "manga", t =>
                        {
                            t.HasCheckConstraint("CK_Series_ContentLanguageCode", "[ContentLanguageCode] IN ('ja','en','vi')");

                            t.HasCheckConstraint("CK_Series_PublicationFrequencyCode", "[PublicationFrequencyCode] IS NULL OR [PublicationFrequencyCode] IN ('WEEKLY','MONTHLY','IRREGULAR')");

                            t.HasCheckConstraint("CK_Series_StatusCode", "[StatusCode] IN ('PROPOSAL_DRAFT','ACTIVE','CANCELLED','ARCHIVED')");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.SeriesBoardPoll", b =>
                {
                    b.Property<long>("SeriesBoardPollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SeriesBoardPollId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PollStatusCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("OPEN");

                    b.Property<string>("PollTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("SeriesId")
                        .HasColumnType("bigint");

                    b.HasKey("SeriesBoardPollId");

                    b.HasIndex("SeriesId", "PollTypeCode")
                        .IsUnique()
                        .HasDatabaseName("ux_series_board_poll_open_type")
                        .HasFilter("[PollStatusCode]='OPEN'");

                    b.ToTable("SeriesBoardPoll", "manga");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.SeriesBoardVote", b =>
                {
                    b.Property<long>("SeriesBoardVoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SeriesBoardVoteId"));

                    b.Property<string>("ChoiceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SeriesBoardPollId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SeriesBoardVoteId");

                    b.HasIndex("UserId");

                    b.HasIndex("SeriesBoardPollId", "UserId")
                        .IsUnique();

                    b.ToTable("SeriesBoardVote", "manga", t =>
                        {
                            t.HasCheckConstraint("CK_SeriesBoardVote_ChoiceCode", "[ChoiceCode] IN ('APPROVE','REJECT','ABSTAIN')");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.SeriesContributor", b =>
                {
                    b.Property<long>("SeriesContributorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SeriesContributorId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SeriesId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SeriesContributorId");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_series_contributor_series_active")
                        .HasFilter("[EndDate] IS NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_series_contributor_user_active")
                        .HasFilter("[EndDate] IS NULL");

                    b.HasIndex("SeriesId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_series_contributor_active_role")
                        .HasFilter("[EndDate] IS NULL");

                    b.HasIndex("SeriesId", "UserId", "StartDate")
                        .IsUnique();

                    b.ToTable("SeriesContributor", "manga", t =>
                        {
                            t.HasCheckConstraint("CK_SeriesContributor_EndDate", "[EndDate] IS NULL OR [EndDate] >= [StartDate]");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.SeriesProposal", b =>
                {
                    b.Property<long>("SeriesProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SeriesProposalId"));

                    b.Property<string>("GenreSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MarkupFileId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProposalFileId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProposalTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("ProposalVersionNo")
                        .HasColumnType("smallint");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<long>("SeriesId")
                        .HasColumnType("bigint");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("UNDER_EDITORIAL_REVIEW");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("SynopsisSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("WithdrawnAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("SeriesProposalId");

                    b.HasIndex("MarkupFileId");

                    b.HasIndex("ProposalFileId");

                    b.HasIndex("ReviewedByUserId")
                        .HasDatabaseName("ix_series_proposal_reviewed_by")
                        .HasFilter("[ReviewedByUserId] IS NOT NULL");

                    b.HasIndex("StatusCode")
                        .HasDatabaseName("ix_series_proposal_status_submitted");

                    b.HasIndex("SubmittedByUserId")
                        .HasDatabaseName("ix_series_proposal_submitted_by");

                    b.HasIndex("SeriesId", "ProposalVersionNo")
                        .IsUnique()
                        .HasDatabaseName("ix_series_proposal_series_version");

                    b.ToTable("SeriesProposal", "manga");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.SeriesRankingSnapshot", b =>
                {
                    b.Property<long>("SeriesRankingSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SeriesRankingSnapshotId"));

                    b.Property<int?>("GeneratedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RankPosition")
                        .HasColumnType("int");

                    b.Property<string>("RankingPeriodTypeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("RankingScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SeriesId")
                        .HasColumnType("bigint");

                    b.HasKey("SeriesRankingSnapshotId");

                    b.HasIndex("GeneratedByUserId");

                    b.HasIndex("SeriesId", "RankingPeriodTypeCode", "PeriodStartDate")
                        .IsUnique();

                    b.ToTable("SeriesRankingSnapshot", "manga", t =>
                        {
                            t.HasCheckConstraint("CK_SeriesRankingSnapshot_RankPosition", "[RankPosition] >= 1");

                            t.HasCheckConstraint("CK_SeriesRankingSnapshot_RankingPeriodTypeCode", "[RankingPeriodTypeCode] IN ('WEEKLY','MONTHLY','SEASONAL')");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<long?>("AvatarFileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("PortfolioFileId")
                        .HasColumnType("bigint");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("PENDING_APPROVAL");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("AvatarFileId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PortfolioFileId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("RoleId", "Status")
                        .HasDatabaseName("ix_users_role_status");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("RoleId", "Status"), new[] { "Username", "Email" });

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_users_status_created");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "CreatedAt"), new[] { "Username", "Email", "RoleId" });

                    b.ToTable("Users", "auth", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Status", "[Status] IN ('PENDING_APPROVAL','ACTIVE','DISABLED')");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.UserRegistrationRequest", b =>
                {
                    b.Property<long>("RegistrationRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RegistrationRequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("PortfolioFileId")
                        .HasColumnType("bigint");

                    b.Property<short>("RequestedRoleId")
                        .HasColumnType("smallint");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("PENDING");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RegistrationRequestId");

                    b.HasIndex("PortfolioFileId");

                    b.HasIndex("RequestedRoleId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_registration_request_pending")
                        .HasFilter("[Status] = 'PENDING'");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_user_registration_status");

                    b.ToTable("UserRegistrationRequest", "auth", t =>
                        {
                            t.HasCheckConstraint("CK_UserRegistrationRequest_Status", "[Status] IN ('PENDING','APPROVED','REJECTED','CANCELLED')");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.AuditEvent", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId");

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.Chapter", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.ChapterEditorialReview", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.Domain.Entities.FileResource", "MarkupFile")
                        .WithMany()
                        .HasForeignKey("MarkupFileId");

                    b.HasOne("MangaManagementSystem.Domain.Entities.User", "ReviewerUser")
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("MarkupFile");

                    b.Navigation("ReviewerUser");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.ChapterPage", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.ChapterPageAnnotation", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.User", "AnnotatedByUser")
                        .WithMany()
                        .HasForeignKey("AnnotatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.Domain.Entities.PageRegion", "PageRegion")
                        .WithMany()
                        .HasForeignKey("PageRegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.Domain.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId");

                    b.Navigation("AnnotatedByUser");

                    b.Navigation("PageRegion");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.ChapterPageTask", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.Domain.Entities.ChapterPageVersion", "CompletedPageVersion")
                        .WithMany()
                        .HasForeignKey("CompletedPageVersionId");

                    b.Navigation("AssignedToUser");

                    b.Navigation("CompletedPageVersion");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.ChapterPageTaskRegion", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.ChapterPageTask", "ChapterPageTask")
                        .WithMany()
                        .HasForeignKey("ChapterPageTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.Domain.Entities.PageRegion", "PageRegion")
                        .WithMany()
                        .HasForeignKey("PageRegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChapterPageTask");

                    b.Navigation("PageRegion");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.ChapterPageVersion", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.ChapterPage", "ChapterPage")
                        .WithMany()
                        .HasForeignKey("ChapterPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.Domain.Entities.FileResource", "PageFile")
                        .WithMany()
                        .HasForeignKey("PageFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChapterPage");

                    b.Navigation("PageFile");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.ChapterReaderVoteSnapshot", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.Domain.Entities.User", "EnteredByUser")
                        .WithMany()
                        .HasForeignKey("EnteredByUserId");

                    b.Navigation("Chapter");

                    b.Navigation("EnteredByUser");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.FileResource", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.PageRegion", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.ChapterPageVersion", "ChapterPageVersion")
                        .WithMany()
                        .HasForeignKey("ChapterPageVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChapterPageVersion");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.Series", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.FileResource", "CoverFile")
                        .WithMany()
                        .HasForeignKey("CoverFileId");

                    b.HasOne("MangaManagementSystem.Domain.Entities.Series", "SourceSeries")
                        .WithMany()
                        .HasForeignKey("SourceSeriesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CoverFile");

                    b.Navigation("SourceSeries");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.SeriesBoardPoll", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.SeriesBoardVote", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.SeriesBoardPoll", "SeriesBoardPoll")
                        .WithMany()
                        .HasForeignKey("SeriesBoardPollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeriesBoardPoll");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.SeriesContributor", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.SeriesProposal", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.FileResource", "MarkupFile")
                        .WithMany()
                        .HasForeignKey("MarkupFileId");

                    b.HasOne("MangaManagementSystem.Domain.Entities.FileResource", "ProposalFile")
                        .WithMany()
                        .HasForeignKey("ProposalFileId");

                    b.HasOne("MangaManagementSystem.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId");

                    b.HasOne("MangaManagementSystem.Domain.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.Domain.Entities.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId");

                    b.Navigation("MarkupFile");

                    b.Navigation("ProposalFile");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Series");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.SeriesRankingSnapshot", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.User", "GeneratedByUser")
                        .WithMany()
                        .HasForeignKey("GeneratedByUserId");

                    b.HasOne("MangaManagementSystem.Domain.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedByUser");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.User", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.FileResource", "AvatarFile")
                        .WithMany()
                        .HasForeignKey("AvatarFileId");

                    b.HasOne("MangaManagementSystem.Domain.Entities.FileResource", "PortfolioFile")
                        .WithMany()
                        .HasForeignKey("PortfolioFileId");

                    b.HasOne("MangaManagementSystem.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvatarFile");

                    b.Navigation("PortfolioFile");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.UserRegistrationRequest", b =>
                {
                    b.HasOne("MangaManagementSystem.Domain.Entities.FileResource", "PortfolioFile")
                        .WithMany()
                        .HasForeignKey("PortfolioFileId");

                    b.HasOne("MangaManagementSystem.Domain.Entities.Role", "RequestedRole")
                        .WithMany()
                        .HasForeignKey("RequestedRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MangaManagementSystem.Domain.Entities.User", "User")
                        .WithMany("RegistrationRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PortfolioFile");

                    b.Navigation("RequestedRole");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MangaManagementSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("RegistrationRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
